HOST_MACHINE_IP = '127.0.0.1'
JANUS_WEBSOCKET_PORT = '8188'
LYNKS_HTTP_PORT = '60000'

JANUS_MEDIA_SINK = 'janusvrwebrtcsink'
JANUS_MEDIA_SRC = 'janusvrwebrtcsrc'

JANUS_WEBSOCKET_ENDPOINT = 'ws://' + HOST_MACHINE_IP + ':' + JANUS_WEBSOCKET_PORT + '/ws'
JANUS_RECONNECT_TIME = 20.0
JANUS_RECONNECT_TRIES = 20

LYNKS_ENDPOINT = 'http://' + HOST_MACHINE_IP + ':' + LYNKS_HTTP_PORT